name: mcq_vault
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔹 UI & Core
  cupertino_icons: ^1.0.8
  easy_sidemenu: ^0.7.1
  data_table_2: ^2.6.0
  provider: ^6.1.2

  # 🔹 Local Database & Files
  sqflite: ^2.4.1
  path: ^1.9.0
  file_picker: ^10.3.3
  pdf: ^3.11.2
  printing: ^5.14.0
  intl: ^0.19.0

  # 🔹 Firebase (Updated to v5+)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3

  # 🔹 Other Utilities
  google_sign_in: ^7.2.0
  connectivity_plus: ^7.0.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png

  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
