// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ-wAIE4PICXJs2bYnvfxLY-W73n2s1ts',
    appId: '1:150027876429:android:f93e312bf9477b2e360404',
    messagingSenderId: '150027876429',
    projectId: 'mcq-vault',
    storageBucket: 'mcq-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvl9h5hMDIHUcYIYgmO-2wf1g0gCWGGNk',
    appId: '1:150027876429:ios:0b8c17130e904770360404',
    messagingSenderId: '150027876429',
    projectId: 'mcq-vault',
    storageBucket: 'mcq-vault.firebasestorage.app',
    androidClientId: '150027876429-dc4182i107u876gi2endqn2rjroes392.apps.googleusercontent.com',
    iosClientId: '150027876429-6g7b4h2be3g9bvdjvecf70c6d3a81der.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcqVault',
  );

}